import { Article } from '@/types/article';

export const mockArticles: Article[] = [
  {
    id: '1',
    title: 'Nigeria\'s Economy Shows Strong Growth in Q2 2026',
    source: 'The Guardian Nigeria',
    published_date: new Date('2026-05-19T10:30:00'),
    image_url: 'https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?w=800&h=400&fit=crop',
    excerpt: 'The Nigerian economy recorded a 4.2% growth rate in the second quarter of 2026, driven by strong performance in the oil and agriculture sectors.',
    category: 'News',
    external_url: '#',
    like_count: 234,
    comment_count: 45,
    cached_at: new Date(),
  },
  {
    id: '2',
    title: 'Bitcoin Surges Past $120,000 as Institutional Adoption Grows',
    source: 'CoinDesk',
    published_date: new Date('2026-05-20T08:15:00'),
    image_url: 'https://images.unsplash.com/photo-1518546305927-5a555bb7020d?w=800&h=400&fit=crop',
    excerpt: 'Bitcoin reached a new all-time high today, crossing the $120,000 mark as major financial institutions continue to increase their crypto holdings.',
    category: 'Crypto',
    external_url: '#',
    like_count: 567,
    comment_count: 123,
    cached_at: new Date(),
  },
  {
    id: '3',
    title: 'Burna Boy Announces World Tour Starting in Lagos',
    source: 'Pulse Nigeria',
    published_date: new Date('2026-05-18T14:20:00'),
    image_url: 'https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=800&h=400&fit=crop',
    excerpt: 'Grammy-winning artist Burna Boy has announced a massive world tour that will kick off with three sold-out shows at the Eko Atlantic City in Lagos.',
    category: 'Entertainment',
    external_url: '#',
    like_count: 892,
    comment_count: 234,
    cached_at: new Date(),
  },
  {
    id: '4',
    title: 'Dangote Cement Shares Rise 15% on Strong Earnings Report',
    source: 'BusinessDay',
    published_date: new Date('2026-05-20T09:45:00'),
    image_url: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=800&h=400&fit=crop',
    excerpt: 'Dangote Cement\'s stock price surged 15% following the release of its Q1 2026 earnings report, which showed a 28% increase in revenue year-over-year.',
    category: 'Stocks',
    external_url: '#',
    like_count: 156,
    comment_count: 34,
    cached_at: new Date(),
  },
  {
    id: '5',
    title: 'Lagos State Launches New Tech Hub in Yaba',
    source: 'TechCabal',
    published_date: new Date('2026-05-19T16:00:00'),
    image_url: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=800&h=400&fit=crop',
    excerpt: 'The Lagos State Government has officially opened a state-of-the-art technology hub in Yaba, aimed at supporting startups and fostering innovation.',
    category: 'News',
    external_url: '#',
    like_count: 445,
    comment_count: 78,
    cached_at: new Date(),
  },
  {
    id: '6',
    title: 'Ethereum 3.0 Upgrade Scheduled for July 2026',
    source: 'CryptoNews',
    published_date: new Date('2026-05-20T11:30:00'),
    image_url: 'https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=800&h=400&fit=crop',
    excerpt: 'The Ethereum Foundation has announced that the highly anticipated Ethereum 3.0 upgrade will go live in July, promising faster transactions and lower fees.',
    category: 'Crypto',
    external_url: '#',
    like_count: 678,
    comment_count: 145,
    cached_at: new Date(),
  },
];
